In [5]:
import pandas as pd

In [8]:
df = pd.read_csv('./children_heights.txt', sep='\t')

In [15]:
import nltk

In [16]:
sents = 'What is this life if full of care we have no time to stand and stare! A thing of beauty is a joy forever.'

In [17]:
nltk.sent_tokenize(sents)

['What is this life if full of care we have no time to stand and stare!',
 'A thing of beauty is a joy forever.']

In [28]:
import numpy as np
A = np.array([[2,3], [2,2]])

In [34]:
A

array([[2, 3],
       [2, 2]])

In [32]:
AINV = np.linalg.inv(A)

In [33]:
np.dot(A,AINV)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [35]:
AINV

array([[-1. ,  1.5],
       [ 1. , -1. ]])