In [1]:
import numpy as np

In [2]:
A = np.array([[2,3],[2,2]])

In [3]:
A

array([[2, 3],
       [2, 2]])

In [4]:
np.sum(A, axis=0)

array([4, 5])

In [6]:
np.sum(A, axis=1)

array([5, 4])

In [7]:
np.dot(A,A)

array([[10, 12],
       [ 8, 10]])

In [9]:
import scipy
import scipy.integrate

In [12]:
def velocity(t):
    return 25 + 10.0*t

In [13]:
distance = scipy.integrate.quad(velocity, 0, 3)

In [14]:
print distance

(120.0, 1.3322676295501878e-12)


In [5]:
import sympy
from sympy import sin, cos
from sympy.abc import x, y

In [6]:
# Differentiate below expression
sympy.diff(x**2 + x**3 + cos(x), x)

3*x**2 + 2*x - sin(x)